### PR TITLE
adding distributionManagement to root pom

### PR DESCRIPTION
**Pull request by kcwire**

### CODE REVIEW

**Comment by kcwire** [comment]
@bradh figured it's time to get the snapshots to publish to the codice nexus.  I setup a job on the codice Bamboo server to do this, but left the pom parameterized so individual developers could deploy to their own maven repos if desired.

**Comment by bradh** [comment]
You're using words that only have vague meaning for me. I trust your understanding of the problem though.

**Comment by kcwire** [comment]
Codice Bamboo job: https://codice.atlassian.net/builds/browse/NITF (builds and deploys the maven artifacts)
Codice Nexus: http://artifacts.codice.org/service/local/repositories/snapshots/content/org/codice/imaging/nitf/codice-imaging-nitf-core/0.2-SNAPSHOT/codice-imaging-nitf-core-0.2-20151123.165803-1.jar

Now developers can just add the codice repo to their pom and use this library.

**Comment by bradh** [comment]
Nice. Easier than I'd imagined.

Did you manually deploy / upload the 0.1-SNAPSHOTs?

**Comment by kcwire** [comment]
I did although we should probably delete the previous SNAPSHOT version.  In the future I think it would be useful to do a release before we up the version number.  That way we can fall back and compare as needed.

**Pull request merged**
