### PR TITLE
made commandList accessors public

### PR DESCRIPTION
**Pull request by kcwire**
[Review on Reviewable](https://reviewable.io/reviews/codice/imaging-nitf/2)

### CODE REVIEW

**Comment by bradh** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[.gitignore, line 9 \[r1\]](https://reviewable.io:443/reviews/codice/imaging-nitf/2#-K29QO_fVq3Xh_hzAAMn)** ([raw file](https://github.com/codice/imaging-nitf/blob/18f108822e35e313c98a4877ccbc525aa0a98d71/.gitignore#L9)):</sup>
Node just for consistency with DDF code?


---

<sup>**[cgm/src/main/java/org/codice/imaging/cgm/CgmParser.java, line 289 \[r1\]](https://reviewable.io:443/reviews/codice/imaging-nitf/2#-K29QggJs19ihXOxlVbO)** ([raw file](https://github.com/codice/imaging-nitf/blob/18f108822e35e313c98a4877ccbc525aa0a98d71/cgm/src/main/java/org/codice/imaging/cgm/CgmParser.java#L289)):</sup>
As mentioned on the Github review, I'd like to see better docs for public API.


---

<sup>**[cgm/src/main/java/org/codice/imaging/cgm/CgmParser.java, line 353 \[r1\]](https://reviewable.io:443/reviews/codice/imaging-nitf/2#-K29QyTLhA-yXuRIYxoz)** ([raw file](https://github.com/codice/imaging-nitf/blob/18f108822e35e313c98a4877ccbc525aa0a98d71/cgm/src/main/java/org/codice/imaging/cgm/CgmParser.java#L353)):</sup>
Better API docs here too.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/imaging-nitf/2)

**Comment by kcwire** [comment]
I was following the example in the unit test to get the image.  It appears the CgmRender needs the command list (although I'm still digging through the code and may be following the test blindly)

https://github.com/codice/imaging-nitf/blob/master/cgm/src/test/java/org/codice/imaging/cgm/CgmParserTest.java#L126

**Comment by bradh** [comment]
I merged the strategy branch - the bad news is that resulted in merge conflicts, but the good news is that already has these as public.

**Comment by kcwire** [comment]
That works for me :+1:

**Pull request closed without merging**
