### PR TITLE
IMG-200 TaggedRecordExtensionHandler throws a NullPointerException fo…

### PR DESCRIPTION
**Pull request by dcruver**
…r some TRE values.

This change adds a null check to prevent an NPE when the TRE value is returned as null.

### CODE REVIEW

**Comment by bradh** [comment]
Is this mitigation for the ENGRDA parsing problem? In general, if a value is missing the TRE is broken / invalid, and I'm reluctant to ignore that. Perhaps some kind of parsing exception instead of NPE?

**Comment by dcruver** [comment]
It's for a similar problem that I'm seeing in HISTOA. The NIPCOM field is incorrectly populated.

 HISTOA_NIPCOM_1 : 0
 HISTOA_NIPCOM_2 : 1

...but there are no actual comments in the TRE.  So when trying to flatten IPCOM_2, we're getting back a null which causes an NPE. We don't want such a small error to cause the whole thing to stop parsing, but I've added a warning message.

**Comment by bradh** [comment]
This is failing checkstyle on Travis.

**Comment by bradh** [comment]
No longer required given other commits.

**Pull request closed without merging**
