### PR TITLE
BR-55 Convert Imaging-nitf to a pipeline job

### PR DESCRIPTION
**Pull request by TonyMorrison**
#### What does this PR do?
Takes the codice/imaging-nitf job and converts it to Jenkins pipeline

#### Who is reviewing it? 
@shaundmorris 
@LinkMJB  

#### Select relevant component teams: 
@codice/security

#### Ask 2 committers to review/merge the PR and tag them here.
@shaundmorris 
@bdeining 

#### How should this be tested?
Three main stages should build after checking out the code
1. Full Build no ITest
2. Full Build
3. Deploy (may not Build for PR build)

Full test result from my repo
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/imaging-nitf_TM/job/master/

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bradh** [comment]
Why is this applicable to Codice Imaging?

**Comment by TonyMorrison** [comment]
@bradh there is a job on Connexta prod Jenkins that runs weekly. As a standard we have been converting these legacy Jenkins jobs to pipelines.

**Comment by bradh** [comment]
Does it need to be in here? It looks Connexta specific, and while I do understand the linkage, if there can only be one `Jenkinsfile`, I'd just like to understand the necessity.

**Comment by shaundmorris** [comment]
@bradh you make a good point. It may not be fully necessary, but is helping with some consistency of builds across projects. I see it as supplemental to the Travis-CI build. However if you believe it is unnecessary and not a good fit we can close this PR.

**Comment by bradh** [comment]
@TonyMorrison  @shaundmorris  I'm OK with it in at this stage, with a "I'll ask for a change if it becomes necessary".
I didn't actually verify the content though - I assume that is being done on your side. Let me know if / when that is done.

**Comment by TonyMorrison** [comment]
We will not go forward at this time. The Jenkins job will be disabled and archived and removed at a later date

**Pull request closed without merging**
