### PR TITLE
Added Class to export RPC metadata as SensorML2

### PR DESCRIPTION
**Pull request by ghobona**

### CODE REVIEW

**Review by bradh — COMMENTED** [review]
Hi @ghobona
I think this needs more background / context to help understand the design and implementation.
It looks like it is extracting some TRE metadata into SensorML XML, but I don't under what the goal is.
What is the intended use of this class? Who would use it?

On first pass, it looks like you probably wanted to filter for a specific TRE (or set of TREs), rather than taking any value that ends with `_COEFF`.

**Comment by ghobona** [comment]
Hi @bradh 

Thanks for spotting the missing filter for TREs. The method is only meant to work with RPC00B TREs. Specifically to enable their export to SensorML 2.0 files.

The method has been tested using a NITF file created using QGIS from the Stereo sample at https://www.isprs.org/data/ikonos/default.aspx

The method can be called as follows, for example.

```java

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import org.codice.imaging.nitf.core.sensorml.impl.RPCSensorML2Writer;

public class Main {

	public static void main(String[] args) {
		try {

			RPCSensorML2Writer writer = new RPCSensorML2Writer();
			writer.write(new FileInputStream("/home/cite/Documents/rpc_sample.ntf"),
					new FileOutputStream("/home/cite/Documents/rpc_sensorml2_output.xml"));

		} catch (Exception er) {
			er.printStackTrace();
		}
	}

}
```

The reason why I am interested in this is that we are developing the Executable Test Suite (ETS) for SensorML 2 and need a few more products to pass the compliance test in order for the  ETS to move from Beta to Production.

**Comment by bradh** [comment]
I'm still not understanding which users would want to export RPC values to SensorML2. I understand that its possible, just not what the use of the resulting SensorML2 file would be. 

If you can open the NITF file, then you have the TRE values. If you can't open the NITF file, then what are you mensurating?

If its just for the ETS, then I'm unconvinced about it being in core. Could it be in another module (probably a new module) along with the CLI harness? I'm still unhappy about the lack of unit testing of the functionality, but that would be slightly less of an issue outside of core.

If we can come to agreement on the issues above, there are also some format (mostly tab) and other issues reported by checkstyle. They're breaking the build. Do a command line `mvn` build to see them.

**Comment by ghobona** [comment]
Hi @bradh

Those are fair points you raise.

Responding to the question "If you can open the NITF file, then you have the TRE values. If you can't open the NITF file, then what are you mensurating?"

Effectively, the idea is to be able to enable applications that can read SensorML, but may not be able to read TREs, to obtain information about the sensor model. This could be for uses such as data curation, linking or re-processing.

Responding to the question "Could it be in another module (probably a new module) along with the CLI harness?"

Yes, I agree. It would be better sitting outside the core. I will move it to a separate module and implement a unit test.

Thanks for your feedback.

**Comment by ghobona** [comment]
Closing the PR. A new PR will be created once the class has been moved into a separate module.

**Pull request closed without merging**
