### PR TITLE
[IMG-246] Fixed NitfInputStreamReader infinite loop

### PR DESCRIPTION
**Pull request by DavidM1A2**
The method NitfInputStreamReader::skip can enter an infinite loop if the input stream has no more bytes to read. This situation can be caused by a corrupt Nitf.

Related JIRA ticket: [IMG-246](https://codice.atlassian.net/browse/IMG-246)

### CODE REVIEW

**Comment by bradh** [comment]
I'm very reluctant to accept this as-is.

From the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#skip-long-): `The skip method may, for a variety of reasons, end up skipping over some smaller number of bytes, possibly 0. This may result from any of a number of conditions; reaching end of file before n bytes have been skipped is only one possibility. `

So some more rigorous checks might be warranted here.

**Comment by DavidM1A2** [comment]
I added additional checks to look for an invalid argument (skipping 0 or a negative number of bytes) which would also cause `InputStream::skip` to return 0. From the docs I can't see another way for `InputStream::skip` returning 0, is this correct?

**Comment by bradh** [comment]
I don't think you can assume that. It could just be UDP streaming over a slow / intermittent link. If that is the case, do we want to throw away the file? 

Maybe if we ask for x bytes (x >0), we loop some reasonable number of times waiting to get to x, then throw?

Another option would be something on the consumer side that aborts the processing if it takes "too long" - whatever that consumer considers unreasonable.

**Comment by DavidM1A2** [comment]
I added a `skipTimeoutMillis` field to `NitfInputStreamReader` that allows the consumer to specify a skip timeout in milliseconds. If this is not specified the default value of 0 is used so current implementations shouldn't need to change anything.

**Comment by bradh** [comment]
I like it. @dcruver anything extra?

**Comment by coyotesqrl** [comment]
My team would very much like to get this fix, but no version 0.8.3 was ever released and version 0.9 includes an upgrade to javax.activation that we cannot take without a massive overhaul.

Would it be possible to create a 0.8.x branch off of the [codice-imaging-nitf-0.8.2](https://github.com/codice/imaging-nitf/tree/codice-imaging-nitf-0.8.2) tag, cherry-pick this change, and get a 0.8.3 release cut?

**Pull request merged**
